import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4.1-nano")

SNOWFLAKE_CONFIG = {
    "account": os.getenv("SNOWFLAKE_ACCOUNT"),
    "user": os.getenv("SNOWFLAKE_USER"),
    "password": os.getenv("SNOWFLAKE_PASSWORD"),
    "warehouse": os.getenv("SNOWFLAKE_WAREHOUSE"),
    "database": os.getenv("SNOWFLAKE_DATABASE"),
    "schema": os.getenv("SNOWFLAKE_SCHEMA"),
    "role": os.getenv("SNOWFLAKE_ROLE")
}

STANDARD_FIELDS = ["ORDER_ID", "LINE_ID", "ORDER_ITEM_ID", "TRANSACTION_ID", "ORDER_CREATION_DATE", "FULFILLMENT_SYSTEM_ORDER_DATE", "ACTUAL_SHIPMENT_DATE", "QTY_ORDERED", "CHANNEL", "STYLE_NAME", "DSKU", "LAUNCHED_DATE_PARTITION_KEY", "VSKU", "JOIN_KEY", "SSKU", "VENDOR_NAME", "VENDOR_ID", "UNIT_COGS", "LINE_REVENUE", "LINE_COGS", "UNIT_SELLING_PRICE", "SHIPPED_QUANTITY", "CUSTOMER_ACCOUNT_NUMBER", "CUSTOMER_CREATION_DATE", "CUSTOMER_FIRST_ORDER_DATE", "SHIPPED_TO_POSTALCODE", "ORDER_STATUS", "ORDER_LINE_STATUS", "UPC", "ITEM_DESCRIPTION", "ITEM_CATEGORY", "ITEM_DEPARTMENT", "ITEM_DIVISION", "ITEM_CLASS", "REORDER_ENABLED", "FULFILLMENT_MODE", "BRAND", "SHIPPING_WEIGHT", "PRODUCT_IMAGE", "SHIP_STATE", "STATE_NAME", "SHIP_COUNTRY", "REGION", "DISCOUNTS", "SHIPPED_FROM", "SHIPPING_SERVICE_LEVEL", "PAYMENT_TYPE", "LATITUDE", "LONGITUDE", "LOCATIONS", "SIZE", "NUMERIC_SIZE", "COLOR", "LAUNCH_DATE", "STYLE_IDENTIFIER", "BASELINE_COHORT", "STAR_RATING", "PRICE_RANGE", "INVENTORY_STYLE_LEVEL", "INVENTORY_SKU_LEVEL", "SHIPPED_STORE", "FULFILLMENT_METHOD", "SALE_TYPE", "CUSTOM_KPI_1", "CUSTOM_1", "CUSTOM_2", "CUSTOM_3", "CUSTOM_4", "CUSTOM_5"]
